### ISSUE TITLE
AboutParametricPolymorphism, test 03

### ISSUE THREAD

**Issue by cynic** [SirMwazv/FSharpKoans#10]
Two things here:

- You don't need to say `MyRecord.Who` and `MyRecord.What` and so on when you're creating it; `Who` and `What` will suffice.
- The types you supply for `ofType` are incorrect, I'm afraid.

**Comment by 3UpKing** [comment]
Updated the records (names not fully qualified anymore)

**Comment by 3UpKing** [comment]
Types changed to correct values
