### ISSUE TITLE
AboutMap, tests 01 & 02 & 03

### ISSUE THREAD

**Issue by cynic** [SirMwazv/FSharpKoans#3]
They work, but can you think of a way to do them tail-recursively?

**Comment by cynic** [comment]
Same correction: this is tail recursive, but inefficient.  Could you make it more efficient?

**Comment by SirMwazv** [comment]
Same method.Now I reversed the lists and then used cons e.g 
|[] -> List.rev newList
               |a::restA -> innerMap (restA) (a+1:: newList)
