### ISSUE TITLE
AboutOtherListFunctions, tests 02 & 03

### ISSUE THREAD

**Issue by cynic** [SirMwazv/FSharpKoans#7]
Can you find a tail-recursive way of doing these?

**Comment by cynic** [comment]
Correction - these *are* tail recursive, but inefficient.  They use concat instead of cons; can you make them more efficient?

**Comment by SirMwazv** [comment]
Hope I've done the right thing. Reversed the lists and then used cons.

**Comment by cynic** [comment]
Looks good. You've got some extra brackets on [this line](https://github.com/SirMwazv/FSharpKoans/blob/192f650798652e92219cea914a322b8ecbc9ab60/FSharpKoans/AboutOtherListFunctions.fs#L42), though.
