### ISSUE TITLE
AboutParametricPolymorphism, test 02

### ISSUE THREAD

**Issue by cynic** [SirMwazv/FSharpKoans#9]
You don't need the brackets here.

**Comment by 3UpKing** [comment]
Test won't pass without use of brackets ( they are being used to group the data)

**Comment by cynic** [comment]
I suspect that you're looking at the wrong line.

**Comment by 3UpKing** [comment]
![fsharpkoans - microsoft visual studio 2018_03_06 3_36_55 pm](https://user-images.githubusercontent.com/36456568/37035259-9fe31e90-2154-11e8-881a-b5aa8c2b3ad0.png)
![fsharpkoans - microsoft visual studio 2018_03_06 3_39_34 pm](https://user-images.githubusercontent.com/36456568/37035260-a01125ec-2154-11e8-8660-2fd79dd09949.png)

Please Clarify if these are the lines in question.

**Comment by 3UpKing** [comment]
The warning highlighted above says "This expression should have type 'unit', but has type 'unit * int * int'. Use 'ignore' to discard the result of the expression, or 'let' to bind the result to a name.	FSharpKoans	C:\Users\tavon\Documents\GitHub\fsharpkoans\FSharpKoans\FSharpKoans\AboutParametricPolymorphism.fs	57	
"

**Comment by cynic** [comment]
Yes, those are the lines in question.  Or, rather, _one_ of those is the line in question; on the other lines, the brackets are needed.

**Comment by 3UpKing** [comment]
![fsharpkoans - microsoft visual studio 2018_03_06 3_56_40 pm](https://user-images.githubusercontent.com/36456568/37036003-09b9cbc8-2157-11e8-8f72-1ccae4e4da38.png)

Okay, This should do it then. Could you please provide a brief explanation of whats happening here in terms of precedence; I suspect that the 'should equal' func only accepts the first value (e.g '4' in line 57) without the brackets, am i correct to assume this? So in other words it doesn't recognize the full input?

**Comment by cynic** [comment]
`f 4 5 |> should equal (4, 5, 5)` is parsed as `(f 4 5) |> (should (equal) (4, 5, 5))`.  Without the brackets on that line, it would be parsed as `((f 4 5) |> (should (equal) (4))), 5, 5`.
